$schema: https://raw.githubusercontent.com/sheldonix/tpull/v1.1.0/schema.json
tpull_version: 1.1.0
name: nuxt-shadcn-template
template_repo: https://github.com/sheldonix/nuxt-shadcn-template
prompts:
  - var: project_name
    type: input
    message: Project name?
    default: my-nuxt-app
    required: true
    validate: ''
replacements:
  - files:
      - package.json
    pattern: '/("name"\s*:\s*")[^"]*(")/'
    replace: '$1{{project_name}}$2'
  - files:
      - tpull-config.yaml
    pattern: '/(^name:\s*)nuxt-shadcn-template/m'
    replace: '$1{{project_name}}'
  - files:
      - tpull-config.yaml
    pattern: '/)nuxt-shadcn-template/g'
    replace: '){{project_name}}'