$schema: https://raw.githubusercontent.com/sheldonix/tpull/v1.0.0/schema.json
tpull_version: 1.0.0
name: nuxt-shadcn-template
template_repo: https://github.com/sheldonix/nuxt-shadcn-template
prompts:
  - var: project_name
    type: input
    message: Project name?
    default: nuxt-shadcn-app
    required: true
    validate: ''
replacements:
  - files:
      - package.json
    pattern: '/("name"\s*:\s*")[^"]*(")/'
    replace: '$1{{project_name}}$2'
  - files:
      - tpull-config.yaml
    pattern: '/(^name\s*:\s*)[^\r\n]*/m'
    replace: '$1{{project_name}}'